/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Numero;

import javax.swing.JOptionPane;

/**
 *
 * @author Acer
 */
public class InterfazNúmero extends javax.swing.JFrame {

    /**
     * Creates new form InterfazNúmero
     */
    public InterfazNúmero() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    AAbstract a = new AAbstract(){
        @Override
        public double operacion(double a, double b) {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

    };
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Num1 = new javax.swing.JTextField();
        Num2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        PanelSuma = new javax.swing.JPanel();
        textoSuma = new javax.swing.JLabel();
        PanelResta = new javax.swing.JPanel();
        textoResta = new javax.swing.JLabel();
        panelDiv = new javax.swing.JPanel();
        textoDiv = new javax.swing.JLabel();
        panelMulti = new javax.swing.JPanel();
        textoMulti = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 153));

        jLabel1.setFont(new java.awt.Font("JetBrains Mono", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Calculadora de Numeros");

        Num1.setText("0");
        Num1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num1ActionPerformed(evt);
            }
        });

        Num2.setText("0");
        Num2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("JetBrains Mono", 0, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Digita Un Primer Numero:");

        jLabel3.setFont(new java.awt.Font("JetBrains Mono", 0, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Digita Un Segundo Numero:");

        PanelSuma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelSumaMouseClicked(evt);
            }
        });

        textoSuma.setText("Sumar");
        textoSuma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textoSumaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PanelSumaLayout = new javax.swing.GroupLayout(PanelSuma);
        PanelSuma.setLayout(PanelSumaLayout);
        PanelSumaLayout.setHorizontalGroup(
            PanelSumaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSumaLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(textoSuma)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelSumaLayout.setVerticalGroup(
            PanelSumaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelSumaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(textoSuma)
                .addContainerGap())
        );

        PanelResta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelRestaMouseClicked(evt);
            }
        });

        textoResta.setText("Restar");
        textoResta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textoRestaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PanelRestaLayout = new javax.swing.GroupLayout(PanelResta);
        PanelResta.setLayout(PanelRestaLayout);
        PanelRestaLayout.setHorizontalGroup(
            PanelRestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRestaLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(textoResta)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelRestaLayout.setVerticalGroup(
            PanelRestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelRestaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(textoResta)
                .addContainerGap())
        );

        panelDiv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelDivMouseClicked(evt);
            }
        });

        textoDiv.setText("Dividir");
        textoDiv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textoDivMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelDivLayout = new javax.swing.GroupLayout(panelDiv);
        panelDiv.setLayout(panelDivLayout);
        panelDivLayout.setHorizontalGroup(
            panelDivLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDivLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(textoDiv)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        panelDivLayout.setVerticalGroup(
            panelDivLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDivLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(textoDiv)
                .addContainerGap())
        );

        panelMulti.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelMultiMouseClicked(evt);
            }
        });

        textoMulti.setText("Multiplicar");
        textoMulti.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textoMultiMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelMultiLayout = new javax.swing.GroupLayout(panelMulti);
        panelMulti.setLayout(panelMultiLayout);
        panelMultiLayout.setHorizontalGroup(
            panelMultiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMultiLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(textoMulti)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelMultiLayout.setVerticalGroup(
            panelMultiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMultiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textoMulti)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(121, 121, 121))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2)
                        .addComponent(Num1, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                        .addComponent(Num2))
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelMulti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelResta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelSuma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelDiv, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Num1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Num2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(PanelSuma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PanelResta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelMulti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelDiv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Num1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num1ActionPerformed
     
    }//GEN-LAST:event_Num1ActionPerformed

    private void Num2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num2ActionPerformed
     
    }//GEN-LAST:event_Num2ActionPerformed

    private void textoSumaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoSumaMouseClicked
 AAbstract suma = new Sumar();
     
        JOptionPane.showMessageDialog(null, suma.operacion(Integer.parseInt(Num1.getText()),Integer.parseInt(Num2.getText())));     
    }//GEN-LAST:event_textoSumaMouseClicked

    private void PanelSumaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelSumaMouseClicked
     AAbstract suma = new Sumar();
     
        JOptionPane.showMessageDialog(null, suma.operacion(Integer.parseInt(Num1.getText()),Integer.parseInt(Num2.getText())));
    }//GEN-LAST:event_PanelSumaMouseClicked

    private void PanelRestaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelRestaMouseClicked
      AAbstract resta = new Restar();
      JOptionPane.showMessageDialog(null,resta.operacion(Integer.parseInt(Num1.getText()),Integer.parseInt(Num2.getText())));
    }//GEN-LAST:event_PanelRestaMouseClicked

    private void textoRestaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoRestaMouseClicked
     AAbstract resta = new Restar();
      JOptionPane.showMessageDialog(null,resta.operacion(Integer.parseInt(Num1.getText()),Integer.parseInt(Num2.getText())));
    }//GEN-LAST:event_textoRestaMouseClicked

    private void textoMultiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoMultiMouseClicked
       AAbstract multi = new Multiplicacion();
        JOptionPane.showMessageDialog(null,multi.operacion(Integer.parseInt(Num1.getText()),Integer.parseInt(Num2.getText())));
    }//GEN-LAST:event_textoMultiMouseClicked

    private void panelMultiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMultiMouseClicked
       AAbstract multi = new Multiplicacion();
        JOptionPane.showMessageDialog(null,multi.operacion(Integer.parseInt(Num1.getText()),Integer.parseInt(Num2.getText())));
    }//GEN-LAST:event_panelMultiMouseClicked

    private void textoDivMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoDivMouseClicked
    AAbstract div = new Division();
      JOptionPane.showMessageDialog(null,div.operacion(Integer.parseInt(Num1.getText()),Integer.parseInt(Num2.getText())));
    }//GEN-LAST:event_textoDivMouseClicked

    private void panelDivMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDivMouseClicked
     AAbstract div = new Division();
      JOptionPane.showMessageDialog(null,div.operacion(Integer.parseInt(Num1.getText()),Integer.parseInt(Num2.getText())));
    }//GEN-LAST:event_panelDivMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazNúmero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazNúmero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazNúmero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazNúmero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazNúmero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Num1;
    private javax.swing.JTextField Num2;
    private javax.swing.JPanel PanelResta;
    private javax.swing.JPanel PanelSuma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelDiv;
    private javax.swing.JPanel panelMulti;
    private javax.swing.JLabel textoDiv;
    private javax.swing.JLabel textoMulti;
    private javax.swing.JLabel textoResta;
    private javax.swing.JLabel textoSuma;
    // End of variables declaration//GEN-END:variables
}
